# Generated by Django 3.2.13 on 2022-07-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
    ]
