# Generated by Django 3.2.18 on 2023-04-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
    ]
